kind: Pod
apiVersion: v1
metadata:
  name: multicontainers
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
    - name: alma 
      image: almalinux 
      command: ['sleep','2000']