kind: Pod
apiVersion: v1 
metadata:
  name: multicontainer 
  labels: 
    name: alma-nginx 
    modules: web 
spec:
  containers:
    - name: nginx
      image: nginx
    
    - name: alma 
      image: alma 
      
    