kind: Pod
apiVersion: v1
metadata: 
  name: annotataion
  labels:
    project: expense 
    environment: development 
    module: frontend 
  annotations: 
    imageregistry: "https://hub.docker.com/"
    created_by: kedarnath@hello
    url: jenkins_URL
spec:
  containers:
    - name: nginx
      image: nginx
