kind: Pod
apiVersion: v1
metadata: 
  name: environment-pod 
  labels:
    module: web 
    project: expense
  annotataions: 
    imageregistry: "https://hub.docker.com/"
    created_by: kedarnath@hello
spec:
  containers:
    - name: nginx 
      image: nginx 
      env:
        - name: course
          value: kubernetes 
        - name: trainer 
          value: kedarnath 
        - name: duration 
          value: 30-hrs 
          
