kind: Pod
apiVersion: v1
metadata: 
  name: environment-01
  labels:
    project: expense 
    environment: development 
    module: frontend 
  annotations: 
    imageregistry: "https://hub.docker.com/"
    created_by: kedarnath@hello
    url: jenkins_URL
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: course
          value: kubernetes 
        - name: trainer 
          value: kedarnath 
        - name: duration 
          value: 30-hrs 

