kind: Pod
apiVersion: v1
metadata: 
  name: resmulticont 
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "128m"
        limits: 
          memory: "64Mi"
          cpu: "128m"

    - name: alma 
      image: almalinux:9 
      command: ["sleep","8000"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "128m"
        limits:
          memory: "64Mi"
          cpu: "128m"
          