kind: Service
apiVersion: v1
metadata: 
  name: exp-service
spec: 
  selector:
    project: expense 
    module: frontend 
    tier: web
    environment: Dev 
    app: expense
  ports:
    - protocol: TCP  
      port: 80 # service port 
      targetPort: 80 # target port 
      
