kind: Service
apiVersion: v1
metadata:
  name: nginx-nodeport 
spec:
  type: NodePort
  selector:
    project: expense 
    module: frontend 
    tier: web
    environment: Dev 
    app: expense 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32969
