kind: service
apiVersion: v1
metadata: 
  name: nginx-lb
spec:
  type: LoadBalancer 
  selector:
    project: expense 
    module: frontend 
    tier: web
    environment: Dev 
    app: expense 
  port:
    - protocol: TCP
      port: 80
      targetPort: 80
      