kind: Service
apiVersion: v1
metadata: 
  name: lb-2 
spec:
  type: LoadBalancer
  selector: 
    project: expense 
    module: frontend 
    tier: web
    environment: Dev 
    app: expense
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32761
